apiVersion: v1
kind: List
items:

- apiVersion: extensions/v1beta1
  kind: ThirdPartyResource
  metadata:
    name: ovirt-node-network-attachment.ovirt.org
  description: "oVirt node network configuraton."
  versions:
  - name: v1alpha1

- apiVersion: extensions/v1beta1
  kind: ThirdPartyResource
  metadata:
    name: ovirt-node-network-info.ovirt.org
  description: "oVirt node network reporting."
  versions:
  - name: v1alpha1

- apiVersion: extensions/v1beta1
  kind: DaemonSet
  metadata:
    labels:
      name: node-network-attachment-handler
    name: node-network-attachment-handler
  spec:
    template:
      metadata:
        labels:
          name: node-network-attachment-handler
      spec:
        serviceAccountName: privilegeduser
        hostNetwork: true
        hostPID: true
        hostIPC: true
        securityContext:
          privileged: true
        containers:
          - name: node-network-attachment-handler
            image: docker.io/phoracek/ovirt-node-network-attachment-handler:latest
            imagePullPolicy: IfNotPresent
            securityContext:
              privileged: true
            volumeMounts:
              - mountPath: /var/lib/vdsm
                name: var-lib-vdsm
              - mountPath: /var/run/dbus
                name: var-run-dbus
              - mountPath: /etc/sysconfig/network-scripts
                name: etc-sysconfig-networkscripts
              - mountPath: /lib/modules
                name: lib-modules
          - name: node-network-info-handler
            image: docker.io/phoracek/ovirt-node-network-info-handler:latest
            imagePullPolicy: IfNotPresent
            securityContext:
              privileged: true
            volumeMounts:
              - mountPath: /var/lib/vdsm
                name: var-lib-vdsm
              - mountPath: /var/run/dbus
                name: var-run-dbus
              - mountPath: /etc/sysconfig/network-scripts
                name: etc-sysconfig-networkscripts
              - mountPath: /lib/modules
                name: lib-modules
        volumes:
          - name: var-lib-vdsm
            hostPath:
              path: /var/lib/vdsm-k8s
          - name: var-run-dbus
            hostPath:
              path: /var/run/dbus
          - name: etc-sysconfig-networkscripts
            hostPath:
              path: /etc/sysconfig/network-scripts
          - name: lib-modules
            hostPath:
              path: /lib/modules
