---
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
metadata:
  name: vdsm-network.ovirt.org
description: "Logical network specification"
versions:
- name: v1alpha1
---
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
metadata:
  name: vdsm-bonding.ovirt.org
description: "Logical bonding specification"
versions:
- name: v1alpha1
---
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
metadata:
  name: vdsm-network-attachment.ovirt.org
description: "Host attachment of logical networks and bondings"
versions:
- name: v1alpha1
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    name: vdsm-net-handler
  name: vdsm-net-handler
spec:
  template:
    metadata:
      labels:
        name: vdsm-net-handler
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      securityContext:
        runAsUser: 0
      containers:
        - name: vdsm-net-handler
          image: phoracek/vdsm-net-handler:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
            runAsUser: 0
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - mountPath: /var/lib/vdsm
              name: var-lib-vdsm
            - mountPath: /var/run/dbus
              name: var-run-dbus
            - mountPath: /var/run/libvirt
              name: var-run-libvirt
            - mountPath: /var/run/openvswitch
              name: var-run-openvswitch
      volumes:
        - name: var-lib-vdsm
          hostPath:
            path: /var/lib/vdsm-k8s
        - name: var-run-dbus
          hostPath:
            path: /var/run/dbus
        - name: var-run-libvirt
          hostPath:
            path: /var/run/libvirt
        - name: var-run-openvswitch
          hostPath:
            path: /var/run/openvswitch